### ISSUE TITLE
Styled components integration

### ISSUE THREAD

**Issue by Blazsoul** [GoogleChromeLabs/container-query-polyfill#26]
Hey guys

First i want to say thank you for this polyfill, finally cqfill that really is maintained.
Just a quick question, do you know if there is a way to combine it in styled-components?

Thanks!

**Comment by JulioC** [comment]
Styled-components won't generate styles with `@container` properly. This appears to be caused by the CSS processor they use, which [doesn't recognize it](https://github.com/thysultan/stylis/blob/d09db4c354110c41654fd817ce101976b078d8f7/src/Enum.js) yet.

I've also tried @emotion/styled, without success.

**Comment by Blazsoul** [comment]
Eventually i did find some workaround
I inserted "@media @container" inside the styled components string and replaced the generated style tags from the html with @container

```js
const styleElement = document.querySelector("yourStyleTag");
styleElement.innerHTML = styleElement.innerHTML.replace(/\@media \@container/g, "@container")
```

**Comment by JulioC** [comment]
@Blazsoul how and when do you get the style tag reference?

**Comment by Blazsoul** [comment]
Whenever they mounted, Personally in my project i inject the styles with StyleSheetManager
So its pretty easy catching the style elements this way, Try to find an easy way to target your styled components style tags

**Comment by devknoll** [comment]
The polyfill should work with any library that generates `<style>` elements. Since this seems like an issue with `styled-components` not supporting the `@container` syntax, I would recommend filing an issue there if this is still a problem. Please feel free to open a new issue here if you run into a problem specific to the polyfill.

Thank you!
