### ISSUE TITLE
Chrome update broke tailwindcss-container-query (which uses container-query-polyfill)

### ISSUE THREAD

**Issue by dsldsl** [GoogleChromeLabs/container-query-polyfill#51]
I've been using a plugin [tailwind-container-query](https://github.com/dgknca/tailwindcss-container-query) which uses container-query-polyfill.

After last week's [stable-channel-update-for-desktop](https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop.html) for Google Chrome on Mac OS, the plugin stopped working.  I dont know which library is broken, but I'd assume the other one since people here would probably notice if there was an issue.  Figured I'd check though - anyone else seeing this or have any ideas?

**Comment by Enebz** [comment]
Hey, I am using tailwind-container-query aswell! After surma left google, devknoll updated the entire container-query-polyfill (alpha version) which has raised a lot of confusion on my part.

I am having these issues (with the latest version, not alpha)

Issue 1
https://github.com/GoogleChromeLabs/container-query-polyfill/issues/23
Solution: https://github.com/GoogleChromeLabs/container-query-polyfill/issues/23#issuecomment-1216849203

Issue 2
https://github.com/GoogleChromeLabs/container-query-polyfill/issues/34
Solution: https://github.com/GoogleChromeLabs/container-query-polyfill/issues/34#issuecomment-1216866099


Both solutions should be fixed in the new version of the polyfill by @devknoll 

I made this to check if the alpha solves issue 2:
https://github.com/Enebz/container-query-demo/tree/alpha
And it works perfectly, however this is not using the tailwind version.

**Anyways**
After installing the alpha version for my project where I use tailwindcss-container-query, nothing works at all. I am not getting issue #23 simply because nothing about it works.

When testing with the latest version (0.1.2), the library works just like it did before the chrome update you are talking about. Where I am still getting error #23 and #34. To fix error #23 I used https://github.com/GoogleChromeLabs/container-query-polyfill/pull/33 this, but issue #34 still remained.

I do not think your issue comes from the chrome update as I have no issues using the latest version on my project.

**Also, can you specify which version of container-query-polyfill you are using?**

**Comment by dsldsl** [comment]
Thanks for the reply.  I do think it's the Chrome update because I was at burning man for a week (no code changes) and came back to it no longer working in Chrome and still working in Safari.

It will take some more time for me to create a clean sandbox example, but here's safari on the left and chrome on the right with a basic text-red tag on the text if a large container size is detected:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/50015/189524402-40e6679e-7b0d-4622-bcfa-8790c6e699fc.png">

This is with `tailwindcss-container-query@1.1.0` and *both* `container-query-polyfill@0.1.2` and `container-query-polyfill@0.2.4`

Using Chrome 105.0.5195.102 (as matching the update blog post link shared above) on MacOS 12.5.

**Comment by Enebz** [comment]
Okay, hmm. I will test some more on my side as I am using exactly the same versions as you.

**Comment by dsldsl** [comment]
Thanks @Enebz - appreciate the responses.  How are you using the libraries?  I'm using like this:

```
 <div className={"container-name-cw"}>
                    <div className={"cq-w-cw-lg:text-blush"}>Red if Large</div>
</div>

```

with this tailwind config:

```
theme: {
        /* using the container queries plugin https://github.com/dgknca/tailwindcss-container-query */
        containerName: {
            cw: 'cardWidget',
            // ...
        },
        containerQuery: {
            lg: '440px',
        },
        /* END */

```

**Comment by dsldsl** [comment]
I was able to solve this by using different syntax and it worked fine.  Will make a note to trace it through more to understand why my syntax worked last week and not this week, but for now it's good.
